// vuejs/mon-projet-vue/src/components/TaskForm.vue
<template>
  <form  @submit.prevent="submitHandler">
    <label for="id"> ID :
      <input type="text" id="id" v-model="task.id">
    </label> <br>
    <label for="title"> Titre :
      <input type="text" id="title" v-model="task.title">
    </label> <br>
    <label for="description"> Descrition :
      <input type="text" id="description" v-model="task.description">
    </label> <br>
    <input type="submit" :value="submitLabel">
  </form>
</template>

<script>
export default {
  props: {
    task: Object,
    action: String
  },
  methods: {
    submitHandler () {
      // emettra l'event addTask ou editTask
      this.$emit(`${this.action}Task`, { ...this.task })
    }
  },
  computed: {
    submitLabel () {
      switch(this.action) {
        case 'add':
          return 'Ajouter la tâche'
          break;
        case 'edit':
          return 'Editer la tâche'
          break;
      }
    }
  }
}
</script>

// react_class/src/TaskForm.js
import React from 'react'

export default class TaskForm extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      id: this.props.value,
      title: this.props.title,
      isDone: false
    }
  }
  
  submitAction = () => {
    console.log(this.props.action)
    let submitName
    switch (this.props.action) {
      case 'add':
        submitName = 'Ajouter'
        break
      case 'edit':
        submitName = 'Editer'
        break
      default:
        submitName = 'Bug'
        break
    }

    return submitName
  }

  handleTaskFormSubmit= (e) => {
    e.preventDefault()
    switch (this.props.action) {
      case 'add':
        this.props.add(this.state)
        break
      case 'edit':
          this.props.edit(this.state)
        break
      default:
        break
    }
    this.setState({
      id: '',
      title: ''
    })
  }

  handleChange = (e) => {
    const itemToChange = e.target.name
    const newState = {
      [itemToChange]: e.target.value
    }
    this.setState({
      ...this.state,
      ...newState
    })
  }

  render () {
    return (
      <form onSubmit={this.handleTaskFormSubmit}>
        <label htmlFor="id">ID :
          <input id="id" type="text" value={this.state.id} name="id" onChange={this.handleChange}/> {this.state.id}
        </label> <br/>
        <label htmlFor="Title">Title :
          <input id="Title" type="text" value={this.state.title} name="title" onChange={this.handleChange}/>
        </label> <br/>
        <input type="submit" value={this.submitAction()}/>
      </form>
    )
  }
}
